# ################################################################################################### #
#                                                                                                     #
#             ███████╗██████╗ ██╗███████╗███╗   ██╗██████╗ ███████╗      ██████╗  ██████╗             #
#             ██╔════╝██╔══██╗██║██╔════╝████╗  ██║██╔══██╗██╔════╝      ██╔══██╗██╔════╝             #
#             █████╗  ██████╔╝██║█████╗  ██╔██╗ ██║██║  ██║███████╗█████╗██████╔╝██║  ███╗            #
#             ██╔══╝  ██╔══██╗██║██╔══╝  ██║╚██╗██║██║  ██║╚════██║╚════╝██╔══██╗██║   ██║            #
#             ██║     ██║  ██║██║███████╗██║ ╚████║██████╔╝███████║      ██████╔╝╚██████╔╝            #
#             ╚═╝     ╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═══╝╚═════╝ ╚══════╝      ╚═════╝  ╚═════╝             #
#                                                                                                     #
#                                                                                                     #
#  This file is part of FriendsBungee, a BungeeCord friends plugin system.                            #
#                                                                                                     #
#  FriendsBungee is free software: you can redistribute it and/or modify                              #
#  it under the terms of the GNU General Public License as published by                               #
#  the Free Software Foundation, either version 3 of the License, or                                  #
#  (at your option) any later version.                                                                #
#                                                                                                     #
#  FriendsBungee is distributed in the hope that it will be useful,                                   #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of                                     #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                                      #
#  GNU General Public License for more details.                                                       #
#                                                                                                     #
#  You should have received a copy of the GNU General Public License                                  #
#  along with this program.  If not, see <https://www.gnu.org/licenses/>.                             #
#                                                                                                     #
# ################################################################################################### #


# ##################################################################################### #
#                                  ╔═╗╦═╗╦╔═╗╔╗╔╔╦╗╔═╗                                  #
#                                  ╠╣ ╠╦╝║║╣ ║║║ ║║╚═╗                                  #
#                                  ╚  ╩╚═╩╚═╝╝╚╝═╩╝╚═╝                                  #
#                                                                                       #
# In this part, you can configure friends system.                                       #
#                                                                                       #
# Parameters supported :                                                                #
#                                                                                       #
#   - %player% : sender                                                                 #
#   - %targetPlayer% : target                                                           #
#                                                                                       #
friends:                                                                                #
# ------------------------------------------------------------------------------------- #

  # Alias of friends commands
  cmdAlias:
    - f
    - friend


# ##################################################################################### #
#                                   ╔═╗╦═╗╔═╗╦ ╦╔═╗╔═╗                                  #
#                                   ║ ╦╠╦╝║ ║║ ║╠═╝╚═╗                                  #
#                                   ╚═╝╩╚═╚═╝╚═╝╩  ╚═╝                                  #
#                                                                                       #
# In this part, you can configure groups system.                                        #
#                                                                                       #
groups:                                                                                 #
# ------------------------------------------------------------------------------------- #

  # Alias of group commands
  cmdAlias:
    - gp
    - party

  # Timing to teleport players in group list :
  timingTP: 1000 # in milliseconds

  # Level groups length (permissions example : fgb.group.custom to fbg.group.custom) :
  lengths:
    # Default group members length (change this entrie name may cause errors) :
    default: 5
    # Custom entries :
    lv10: 10
    custom1: 15
    test: 20

  # Group messages command aliases
  msg:
    # Alias of group private messages commands
    cmdAlias:
      - gpm
      - gpmp



# ##################################################################################### #
#                     ╔═╗╦═╗╦╦  ╦╔═╗╔╦╗╔═╗  ╔╦╗╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗╔═╗                    #
#                     ╠═╝╠╦╝║╚╗╔╝╠═╣ ║ ║╣   ║║║║╣ ╚═╗╚═╗╠═╣║ ╦║╣ ╚═╗                    #
#                     ╩  ╩╚═╩ ╚╝ ╩ ╩ ╩ ╚═╝  ╩ ╩╚═╝╚═╝╚═╝╩ ╩╚═╝╚═╝╚═╝                    #
#                                                                                       #
# In this part, you can configure private messages system.                              #
#                                                                                       #
msg:                                                                                    #
# ------------------------------------------------------------------------------------- #

  # Alias of message commands :
  cmdAlias:
    # Alias for /message command :
    send:
      - mp
      - msg
      - w
      - tell

    # Alias for /resend command :
    resend:
      - r

    # Alias for /report command :
    report:
      - rpt

  # Anti spam :
  antiSpam:
    # Turn to true to enable anti-spam cool down :
    use: false

    # Make cool down in seconds. Default: 5 :
    cool_down: 5

    # Anti Spam level :
    #
    #  - level 1: private message only
    #  - level 2: public message only
    #  - level 3: commands only
    #  - level 4: private and public messages
    #  - level 5: private chat only and commands
    #  - level 6: public chat only and commands
    #  - level 7: public/priavate chat and commands
    #
    level: 2

  # Reports part :
  report:

    # Report command admins perm :
    admPerm: "fbg.reports.admin"

    # Key format to listing reports list :
    keyForm: "&f| &f%key% &f|- "

    # Report reasons available on command /report <reason> <description> :
    reasons:
      - bug
      - bugs
      - lag
      - lags
      - complaints
      - claim


# ##################################################################################### #
#                                    ╔╦╗╦ ╦╔═╗╔═╗ ╦                                     #
#                                    ║║║╚╦╝╚═╗║═╬╗║                                     #
#                                    ╩ ╩ ╩ ╚═╝╚═╝╚╩═╝                                   #
#                                                                                       #
# For the connection to work you just need to create an empty database and configure    #
# the fields that the plugin must take into account and it will take care of the rest!  #
#                                                                                       #
# !! Colors does not work in mysql !!                                                   #
#                                                                                       #
mysql:                                                                                  #
# ------------------------------------------------------------------------------------- #

  # Change to true for use DataBase connection :
  use: false

  # Name of the database to connect to, use the name of your database so that you don't have an error.
  # This parameter is the only one that requires you to intervene in your dataBase :
  dbName: "friendsBG"

  # Database tables prefix, leave blank so as not to use it :
  prefixTables: "tm_"

  # Tables automatically added by plugin in your database:
  profilesTable: "profiles"
  friendsTable: "friends"
  teamsTable: "teams"

  # DataBase login, use your DataBase logins for connect this plugin to your DataBase :
  host: "localhost"
  port: 3306
  user: "user"
  password: "password"

  # This is number of pool connexions established by the plugin :
  maxPoolSize: 10 # Default = 10 database connexions

  # This is max lifetime of pools in ms :
  maxLifeTime: 600000 # Default = 10 minutes -> 600 000 ms

  # This is time out for pools not used :
  poolTimeout: 300000 # Default = 5 minutes -> 300 000 ms

  # This is time to detect data leak :
  dataLeak: 300000 # Default = 5 minutes -> 300 000 ms

  # This is time out for no pool available :
  timeout: 10000 # Default = 10 seconds -> 10 000 ms


# ##################################################################################### #
#                                     ╦═╗╔═╗╔╦╗╦╔═╗                                     #
#                                     ╠╦╝║╣  ║║║╚═╗                                     #
#                                     ╩╚═╚═╝═╩╝╩╚═╝                                     #
#                                                                                       #
# For use this, you need to install and configure Redis-server on GNU/LINUX or Windows  #
# server. This software is an in-memory database system.                                #
#                                                                                       #
# It can be used as an alternative to MariaDB/MySQL servers.                            #
#                                                                                       #
# !! Colors does not work in redis !!                                                   #
#                                                                                       #
redis:                                                                                  #
# ------------------------------------------------------------------------------------- #

  # Change to true for use redis connection :
  use: false

  # Redisson login, use your Redisson logins for connect this plugin to your Redis server :
  host: "localhost"
  port: 6379
  password: "password"
  clientName: "friendsBG"

  # DataBase connection pool used for get and set information :
  dataBase: 1 # Default = 1

  # This is number of allocated threads to redis server :
  threads: 1 # Default = 1

  # This is number of allocated Netty threads to redis server :
  nettyThreads: 1 # Default = 1


# ##################################################################################### #
#                                 ╦ ╦╔═╗╔╦╗╔═╗╔╦╗╔═╗╔═╗                                 #
#                                 ║ ║╠═╝ ║║╠═╣ ║ ║╣ ╚═╗                                 #
#                                 ╚═╝╩  ═╩╝╩ ╩ ╩ ╚═╝╚═╝                                 #
#                                                                                       #
updates:                                                                                #
# ------------------------------------------------------------------------------------- #

  # Turn to true/false for enable/disable plugin updates checker (Available) :
  checker: true

  # Send message to admins (not available) :
  adminMsg:
    # Turn to true to enable update warning :
    use: false
    # Admin permission to resave update message :
    permission: "fbg.update.admin"
    # Message design :
    prefix: "&f[&6UpdateChecker&f] "
    suffix: "&f&l->&f "
    message: "&6New update is available !"


# #################### Plugin made by PataPom - Licensed under GPL3 License. #################### #